version: "3.5"
services:
  book-server:
    container_name: book-server
    restart: always
    networks: 
      - Book-network
    build: ./server
    ports:
      - "3001:8750"
  book-web:
    container_name: book-web
    restart: always
    networks: 
      - Book-network
    build: ./alexandria-web/
    ports:
      - "3000:80"
  book-mongo:
    container_name: book_DB
    networks: 
      - Book-network
    image: mongo

networks:
  Book-network:
    name: Book-network